### ISSUE TITLE
Policy Expressions ordering vs Policy Pattern Sets

### ISSUE THREAD

**Issue by jeanmichelaudet** [cstalhood/Get-ADCVServerConfig#4]
Hi Carl,

This is not a big issue but you should consider the usage of Pattern Set (PS), String Map (SM) and DataSet (DS) in Policy Expression. So, when you output the conf file, Policy Expression should appear after the PS, SM or DS.

The code ordering is good but the output file is not in the correct order.

![image](https://user-images.githubusercontent.com/43753300/55354328-76b4d900-5493-11e9-99b9-7a6b31a64d7b.png)

Thanks!

**Comment by cstalhood** [comment]
Thanks for noticing that. I moved it lower in the output.
