### ISSUE TITLE
Content switch related services not extracted

### ISSUE THREAD

**Issue by felipe1982** [cstalhood/Get-ADCVServerConfig#5]
This tool does not appear to extract CS related objects from my ns.conf.

See a sample:
```conf
add server srv_lb_aws.rada.example.com.au 10.251.12.35
add lb vserver lb_aws.rada.example.com.au SSL 10.251.12.35 443 -persistenceType NONE -cltTimeout 180
add lb vserver lb_aws.rada.example.com.au_464 SSL 10.251.12.35 464 -persistenceType NONE -cltTimeout 180
bind lb vserver lb_aws.rada.example.com.au svcg_https_aws.rada.example.com.au
bind lb vserver lb_aws.rada.example.com.au_464 svcg_https_aws.rada.example.com.au
bind cs vserver cs_vsrv_byod -policyName cs_pol_rada.example.com.au -targetLBVserver lb_aws.rada.example.com.au -priority 260
add gslb service svc_gslb_aws.rada_AZ1 srv_lb_aws.rada.example.com.au SSL 464 -publicIP 52.64.146.150 -publicPort 464 -maxClient 0 -siteName AZ1 -cltTimeout 180 -svrTimeout 360 -downStateFlush ENABLED
bind ssl vserver lb_aws.rada.example.com.au -certkeyName wildcard.rada.example.com.au2
bind ssl vserver lb_aws.rada.example.com.au_464 -certkeyName wildcard.rada.example.com.au2
```

The output does not have `bind cs vserver...` in it. But it should.

**Comment by cstalhood** [comment]
Are you extracting the lb vserver? Or are you extracting the cs vserver? If you extract only the lb vserver, do you want it to also automatically extract the entire cs vserver? Or just the cs vserver binding?

If you are extracting the cs vserver, then I don't see the "add cs vserver" command in your example.

**Comment by felipe1982** [comment]
In my config, there are 3 CS vservers, but many dozens of LB ververs which back them. When I export a LB vserver, it would be a nice feature to also export the fronting CS vserver which goes along with it. 

If I select both the LB and CS vservers with this script, I get more config than required to run _just_ my LB vserver.

My use case is:
I am trying to "migrate" configuration from one netscaler to another pre-existing netscaler (production!). I am not a netscaler expert. I have elected to migrate every LB vserver as "an application". The CS vserver on the dest NS already exists, and already configured. I just want to add a new LB vserver "and plug it in to" the existing CS vserver (i.e. bind cs vserver XYZ ...)

I am migrating vserver-by-vserver so I can test each application one-by-one before doing a complete DNS cutover to the new dest NS. Both are production NS instances (in AWS...).

(With your help I now realise that the title of the issue is not warranted: this script does **not** omit the CS details. It was my inaccurate expectations)

**Comment by cstalhood** [comment]
Sorry for the delay. If you add the" -cswBind" switch, then it should show you the CS bindings. Does that meet your needs?
